[project]
name = "scheduling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ortools>=9.14.6206",
    "py2wasm>=2.6.2",
    "openpyxl>=3.1.2",
]
